# -*- coding: utf-8 -*-
"""regex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X9O0t8o40uuy96SNxyvSToqK1I84B3PA

1. In the regex created from r'(\d\d\d)-(\d\d\d-\d\d\d\d)', what does group 0 cover? Group 1?
Group 2?
"""

import re
exp = re.search(r'(\d\d\d)-(\d\d\d-\d\d\d\d)','628-177-7859')
#Group-0
print(f"Group 0 covers:{exp.group(0)}")
#Group-1
print(f"Group 1 covers:{exp.group(1)}")
#Group-2
print(f"Group 2 covers:{exp.group(2)}")

"""2. Find website URLs that begin with http:// or https://."""

import re

text = '''If you are getting started with data science, a great place to begin is the official Python documentation available at https://docs.python.org/3/
, which explains core language concepts clearly. For data analysis and manipulation, many learners rely on pandas, whose documentation can be found at https://pandas.pydata.org/docs/
. Another essential library is NumPy, and its user guide at https://numpy.org/doc/
 is frequently referenced by professionals. Those interested in machine learning often explore tutorials on https://scikit-learn.org/stable/tutorial/index.html
, while deep learning enthusiasts check resources hosted on https://www.tensorflow.org/learn
 and https://pytorch.org/tutorials/
. For structured courses, platforms like https://www.coursera.org
 and https://www.edx.org
 offer data science programs created by top universities. Practical coding practice is available on https://www.kaggle.com
, which also hosts datasets and competitions widely used in the industry.'''

# url = re.search(r'^(https?://)[a-zA-Z0-9.-]+',text)
urls = re.search(r'https?://\S+',text)
urls = re.findall(r'https?://\S+',text)

print(urls)

"""3. Clean up dates in different date formats (such as 3/14/2015, 03-14-2015, and 2015/3/14) by
replacing them with dates in a single, standard format.
"""

import re

text = "Date formats are 3/14/2015, 03-14-2015, and 2015/3/14."

date_pattern = r'\d{1,4}[/-]\d{1,2}[/-]\d{1,4}'

dates = re.findall(date_pattern,text)

# print(dates)
def split_date(date):
  if '/' in date:
    parts = date.split('/')
  else:
    parts = date.split('-')
  return parts

def classify_date(parts):
  if len(parts[0]) == 4:
    return 'yyyy/mm/dd'
  elif len(parts[2]) == 4:
    return 'dd/mm/yyyy'

def normalize(parts):
  fmt = classify_date(parts)
  if fmt == 'yyyy/mm/dd':
    return f"{parts[2]}/{parts[1]}/{parts[0]}"
  else:
    return f"{parts[0]}/{parts[1]}/{parts[2]}"

transform = {}

for date in dates:
  parts = split_date(date)
  transform[date] = normalize(parts)

for old,new in transform.items():
  text = text.replace(old,new)

print(text)

"""4. How would you write a regex that matches a number with commas for every three digits? It
must match the following:
•​
'42'
•​
'1,234'
•​
'6,368,745'
but not the following:
•​
'12,34,567' (which has only two digits between the commas)
•​
'1234' (which lacks commas)


"""

import re

text = "How would you write a regex that matches a number with commas for every three digits? It must match the following: •​'42' •​'1,234' •​'6,368,745' but not the following: •​'12,34,567' (which has only two digits between the commas) •​'1234' (which lacks commas)"

# pattern = r'\d{1,3}([,]\d{3})*'
pattern = r'\b\d{1,3}(?:,\d{3})*\b'

print(re.findall(pattern, text))

"""5.
The regex must match the following:
•​
'Satoshi Nakamoto'
•​
'Alice Nakamoto'
•​
'RoboCopNakamoto'
but not the following:
•​
'satoshiNakamoto' (where the first name is not capitalized)
•​
'Mr. Nakamoto' (where the preceding word has a nonletter character)
•​
'Nakamoto' (which has no first name)
•​
'Satoshi nakamoto' (where Nakamoto is not capitalized)
"""

import re

text = '''
The regex must match the following:
•​
'Satoshi Nakamoto'
•​
'Alice Nakamoto'
•​
'RoboCopNakamoto'
but not the following:
•​
'satoshiNakamoto' (where the first name is not capitalized)
•​
'Mr. Nakamoto' (where the preceding word has a nonletter character)
•​
'Nakamoto' (which has no first name)
•​
'Satoshi nakamoto' (where Nakamoto is not capitalized)'''

pattern = re.findall(r'[A-Z][a-zA-Z]*\s?Nakamoto',text)
print(pattern)

"""6. How would you write a regex that matches a sentence where the first word is either Alice, Bob,
or Carol; the second word is either eats, pets, or throws; the third word is apples, cats, or
baseballs; and the sentence ends with a period? This regex should be case-insensitive.
"""

import re

text = '''Alice eats apples.
Bob pets cats.
Carol throws baseballs.
Alice throws Apples.
BOB EATS CATS.
RoboCop eats apples.
ALICE THROWS FOOTBALLS.
Carol eats7 cats.'''

match_pattern = re.findall(r'^(Alice|Bob|Carol) (eats|pets|throws) (apples|cats|baseballs)(\.)$',text,re.IGNORECASE | re.MULTILINE)
print(match_pattern)

"""7. Strong Password Detection Write a function that uses regular expressions to make sure the
password string it is passed is strong. A strong password is defined as one that is at least eight
characters long, contains both uppercase and lowercase characters, and has at least one digit.
You may need to test the string against multiple regex patterns to validate its strength.


"""

import re
passwords = "Ey0D{jI33Q , 12345678 , abcd1234 , Zeq71OK&i48"


def is_strong_password(password):
    if not re.search(r'.{8,}', password):
        return False
    if not re.search(r'[a-z]', password):
        return False
    if not re.search(r'[A-Z]', password):
        return False
    if not re.search(r'[0-9]', password):
        return False
    return True

for password in passwords.split():
  if is_strong_password(password):
    print(f"{password} is a strong password")